### ISSUE TITLE
[BUG]解析失败，arr is not iterable(cannot read property undefined)

### ISSUE THREAD

**Issue by unlimitwhitenight** [dawn-lc/IwaraDownloadTool#130]
**问题描述**

在playlist上批量下载，部分视频解析失败，提示: TypeError: arr is not iterable(cannot read property undefined)

**重现步骤**

重现此问题的步骤：
1. 加载插件后，进入“https://www.iwara.tv/playlist/500be036-cc32-4485-a468-380264ea588c”
2. 视频全选，点下载所选
3. 部分视频可以下载，部分视频解析错误

**截图**
![2023629-141751](https://github.com/dawn-lc/IwaraDownloadTool/assets/14921482/33d5a9f7-d579-45c9-99af-67d8fd786ed6)
![2023629-142529](https://github.com/dawn-lc/IwaraDownloadTool/assets/14921482/dd087049-6f66-4e4c-809f-9b4fcafe2667)

**报错信息**
 - 视频信息解析失败，TypeError: arr is not iterable(cannot read property undefined)

**环境信息**
 - 操作系统：Windows 10
 - 浏览器：Chrome
 - 浏览器版本：114.0.5735.198
 - 脚本管理器：Tampermonkey
 - 下载模式：Aria2

**Comment by dawn-lc** [comment]
请使用最新开发版试试，应该修复了该问题
