### ISSUE TITLE
[Bug]: 重命名里的author好像没生效

### ISSUE THREAD

**Issue by YURICORN** [dawn-lc/IwaraDownloadTool#151]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

如题
下载器是xdown

### 如何复现

1. 前往 '...'
2. 点击 '....'
4. 出现问题

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

3.1.213

### 下载模式是？

Others

### 截图

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/43528141/e98c9737-2677-4751-9cdd-dc122138e965)
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/43528141/c69bb062-151a-40f2-b436-1f2c0f354844)

**Comment by YURICORN** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/43528141/59c57f79-e0e5-4528-8e3c-6c188963d3fa)
jie截图发错了

**Comment by dawn-lc** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/30336566/ce26d8da-3ce8-4505-8fdc-d36862b02e65)

**Comment by dawn-lc** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/30336566/c8465e7f-9ca6-4ad7-b34d-d14b47e4c846)

**Comment by dawn-lc** [comment]
符合预期的输出，请检查重命名模板是否正确。

**Comment by YURICORN** [comment]
解决了，谢谢
