### ISSUE TITLE
[增强]: 可否增添选择下载画质的功能

### ISSUE THREAD

**Issue by TakeshitaMori** [dawn-lc/IwaraDownloadTool#170]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

可否增添选择下载画质的功能，大量视频下载Source资源有些挤占空间

### 如何复现

NONE

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.1.299

### 下载模式是？

Others

**Comment by dawn-lc** [comment]
打开您使用的脚本管理器，将脚本管理器的配置模式改为初学者及以上，点击本脚本，打开存储，在配置文件尾部添加`,
    "priority": {
        "Source": 100,
        "540": 2,
        "360": 1
     }`

**Comment by dawn-lc** [comment]
你想优先下载哪个品质就将哪个品质的对应数字修改至最大

**Comment by dawn-lc** [comment]
更新脚本至开发版并关闭源画质检查选项

**Comment by TakeshitaMori** [comment]
![Screenshot 2024-01-27 133900](https://github.com/dawn-lc/IwaraDownloadTool/assets/59041201/4582fdd3-d147-498d-abf7-775779a34126)
直接在尾部添加会出现eslint:null-Parsing error:lnexpected token
经查找发现在这里可以修改，无需新添
已解决，感谢

**Comment by dawn-lc** [comment]
> ![Screenshot 2024-01-27 133900](https://private-user-images.githubusercontent.com/59041201/300154314-4582fdd3-d147-498d-abf7-775779a34126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzA4NDcsIm5iZiI6MTcwNjMzMDU0NywicGF0aCI6Ii81OTA0MTIwMS8zMDAxNTQzMTQtNDU4MmZkZDMtZDE0Ny00OThkLWFiZjctNzc1Nzc5YTM0MTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA0NDIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjg0NjBmZmU2NTA0YzhmMzdmZDA4MzVjZTNkYjRiYzAzNzhmYjZlNjJkYTUyMGVkYTMxNzIxZDRhZTE1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d2ZxVH4z4j4oNLAkmaLlui8lI6oQMxAfofN1HAFngpk) 直接在尾部添加会出现eslint:null-Parsing error:lnexpected token 经查找发现在这里可以修改，无需新添 已解决，感谢

把最后的}替换成以下内容试试
```
,
    "priority": { "Source": 1, "540": 2, "360":3 },
    "checkPrioritySource": false
}
```

**Comment by dawn-lc** [comment]
另外个人建议，360画质太差，540相对比较合适
