### ISSUE TITLE
[Bug]: 下载可用变量有误

### ISSUE THREAD

**Issue by CrazyDoge666** [dawn-lc/IwaraDownloadTool#181]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

下载模式other自动转跳到IDM下载
![QQ截图20240228170540](https://github.com/dawn-lc/IwaraDownloadTool/assets/36259181/06b93ae3-b824-4f0d-be4f-81859d148979)

使用默认的/Iwara/%#AUTHOR#%/%#TITLE#%[%#ID#%].mp4下载时前面的iwara和%#AUTHOR#%会被忽略。
输出的只有视频标题+视频ID.mp4
不是iwara 作者 视频标题+视频ID.mp4
并且发布时间 %#UploadTime#%这个变量加进去就只会输出乱码文件名

### 如何复现

1. 前往 'iwara下载视频'
2. 点击 '勾选视频并下载'
4. 出现问题。输出文件名不正确

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

正式版3.1.325

### 下载模式是？

Others

**Comment by dawn-lc** [comment]
%#UploadTime#% 变量报错或者输出的乱码有吗，我怀疑是格式转换问题

**Comment by dawn-lc** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/30336566/162c6656-505c-43e2-908d-5ff2ca99309e)
我知道问题在哪了，没传递时间格式参数，导致时间通过默认的JSON.stringify()序列化了

**Comment by dawn-lc** [comment]
others 模式由于浏览器或下载器安全限制无法指定下载目录，这一点是脚本无法控制的，但是Aria2可以通过rpc创建下载任务并指定下载位置，如果你知道IDM的创建任务api请直接修改 function othersDownload

**Comment by dawn-lc** [comment]
如果想要下载到指定文件夹或目录中请使用Aria2、IwaraDownloader或Browser(注：Browser只能在浏览器设置的下载文件夹下创建指定目录)

**Comment by CrazyDoge666** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/36259181/389e6eed-a2f5-40ba-b443-790d3d491358)
/Iwara/%#AUTHOR#%/%#TITLE#%[%#ID#%]/%#UploadTime#%.mp4。加上后只输出时间了

**Comment by CrazyDoge666** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/36259181/e81b2bd4-3db0-4e26-b0f2-40f559b4c852)
/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4
这个发布时间和作者责被忽略掉了只有视频标题和视频ID

**Comment by CrazyDoge666** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/36259181/233f0868-d3d2-4120-8953-ebf059f6e6e1)
/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4
这个的作者和时间则被忽略只输出作品标题和作品ID

**Comment by CrazyDoge666** [comment]
我测试发现在其他页面如关注业和进入视频详情页点击下载发出的文件标题也不一样。
以为/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4
在其他页面下载发送的标题是：角楯 カリン(AUDIO)[jhgzyqngbn6upm].mp4
进入视频详情页面发送的标题：Iwara - 角楯 カリン（AUDIO） [JHgZYQNgbn6upm] [Source].mp4
但是依然都没有作者和发布时间

**Comment by dawn-lc** [comment]
> 我测试发现在其他页面如关注业和进入视频详情页点击下载发出的文件标题也不一样。 以为/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4 在其他页面下载发送的标题是：角楯 カリン(AUDIO)[jhgzyqngbn6upm].mp4 进入视频详情页面发送的标题：Iwara - 角楯 カリン（AUDIO） [JHgZYQNgbn6upm] [Source].mp4 但是依然都没有作者和发布时间

试试`Iwara %#AUTHOR#% %#UploadTime#% %#TITLE#%[%#ID#%].mp4`

**Comment by dawn-lc** [comment]
> 我测试发现在其他页面如关注业和进入视频详情页点击下载发出的文件标题也不一样。 以为/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4 在其他页面下载发送的标题是：角楯 カリン(AUDIO)[jhgzyqngbn6upm].mp4 进入视频详情页面发送的标题：Iwara - 角楯 カリン（AUDIO） [JHgZYQNgbn6upm] [Source].mp4 但是依然都没有作者和发布时间

'/'是路径分割符，用于分割文件夹与文件名

**Comment by dawn-lc** [comment]
`/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4`这段路径的意思是下载文件到`/Iwara/%#AUTHOR#%/%#UploadTime#%/`文件夹下并重命名为`%#TITLE#%[%#ID#%].mp4`

**Comment by dawn-lc** [comment]
> `/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4`这段路径的意思是下载文件到`/Iwara/%#AUTHOR#%/%#UploadTime#%/`文件夹下并重命名为`%#TITLE#%[%#ID#%].mp4`

而在others 模式下“下载文件到`/Iwara/%#AUTHOR#%/%#UploadTime#%/`文件夹下”不起效的原因是 [这里](https://github.com/dawn-lc/IwaraDownloadTool/issues/181#issuecomment-1968655890)

**Comment by CrazyDoge666** [comment]
> > 我测试发现在其他页面如关注业和进入视频详情页点击下载发出的文件标题也不一样。 以为/Iwara/%#AUTHOR#%/%#UploadTime#%/%#TITLE#%[%#ID#%].mp4 在其他页面下载发送的标题是：角楯 カリン(AUDIO)[jhgzyqngbn6upm].mp4 进入视频详情页面发送的标题：Iwara - 角楯 カリン（AUDIO） [JHgZYQNgbn6upm] [Source].mp4 但是依然都没有作者和发布时间
> 
> 试试`Iwara %#AUTHOR#% %#UploadTime#% %#TITLE#%[%#ID#%].mp4`

输出正常了感谢

**Comment by CrazyDoge666** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/36259181/a9ca29a7-c728-4244-a1f0-aa39bf9e6fa6)
有些作者ID直接变成userXXXX了

**Comment by dawn-lc** [comment]
> ![image](https://private-user-images.githubusercontent.com/36259181/310133905-a9ca29a7-c728-4244-a1f0-aa39bf9e6fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTcxNDksIm5iZiI6MTcwOTY1Njg0OSwicGF0aCI6Ii8zNjI1OTE4MS8zMTAxMzM5MDUtYTljYTI5YTctYzcyOC00MjQ0LWExZjAtYWEzOWJmOWU2ZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE2NDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNjBjMjI1ODg1MjVjYjRiODJiYTMxNWFmOTQ4Yjk1Yjg1YzgzYmY2ZTY2NjM4YzM5NjM1ZGZiOTY1M2RiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xiLlEirv8e-v67o8qefvPb5MvVdYAp_rxA0PGoN5IzA) 有些作者ID直接变成userXXXX了

#57
