### ISSUE TITLE
[Bug]: 更新后无法使用

### ISSUE THREAD

**Issue by asps1726** [dawn-lc/IwaraDownloadTool#187]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

更新后无法使用，有尝试安装旧版本且使用正常

### 如何复现

1. 前往 iwara
2. 没有显示UI

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.5

### 下载模式是？

Others

**Comment by asps1726** [comment]
![pic 20240320153602](https://github.com/dawn-lc/IwaraDownloadTool/assets/48749518/1da6cc1e-9ab8-4539-b020-f9041ecbdaf9)
已经尝试重新安装油猴和脚本，均无效

**Comment by asps1726** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/48749518/f92761e6-c5c4-45d0-ae85-a3443b088d29)
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/48749518/f6cbeb2f-c78f-4c37-aa64-390ec4665117)
这个对吗，不好意思麻烦了

**Comment by dawn-lc** [comment]
更新至最新开发版，看看错误是否修复

**Comment by asps1726** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/48749518/dcf0d203-1506-4d12-b58b-90aa3ccbf4ac)
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/48749518/7fcee640-ba28-4888-906e-59ee31bd50d1)
变这样了

**Comment by dawn-lc** [comment]
> ![image](https://private-user-images.githubusercontent.com/48749518/314420098-dcf0d203-1506-4d12-b58b-90aa3ccbf4ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjUyMTUsIm5iZiI6MTcxMDkyNDkxNSwicGF0aCI6Ii80ODc0OTUxOC8zMTQ0MjAwOTgtZGNmMGQyMDMtMTUwNi00ZDEyLWI1OGItOTBhYTNjY2JmNGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4NTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzRjMWQzNWZjMWE4MGJlNGI3ZjFlNmFlOGVjMmFlNmVlZGEyN2ViM2EzOWM4MmI1Mjk2YmFhOWVkMGI0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQe6-G0LinkhilPexT3alMaJKehGF1ZxWGg1StdC_6w) ![image](https://private-user-images.githubusercontent.com/48749518/314420221-7fcee640-ba28-4888-906e-59ee31bd50d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjUyMTUsIm5iZiI6MTcxMDkyNDkxNSwicGF0aCI6Ii80ODc0OTUxOC8zMTQ0MjAyMjEtN2ZjZWU2NDAtYmEyOC00ODg4LTkwNmUtNTllZTMxYmQ1MGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4NTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjU5ZjFhZGYxZGE4ZDIyNjlkNjkzYjE1NTQzZmIzN2Y1ZDVkNDExODQ2ZGY4NTYzMjU3MzAzZjViNDI1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5sYGNWuNS8oeEPes031LoGZtxW76NBiD5u3JL0xEd6k) 变这样了

再更新一下，已经修复后的代码已经推送到开发版了

**Comment by dawn-lc** [comment]
主要是你这个问题我的使用环境复现不了，所以只能根据报错尝试修复了

**Comment by asps1726** [comment]
可以正常使用了，谢谢
