### ISSUE TITLE
[Bug]: 下载栏不加载

### ISSUE THREAD

**Issue by TPAXcc** [dawn-lc/IwaraDownloadTool#193]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/91980905/10116575-25c1-4a46-abe0-b418867654c9)

### 如何复现

1. 前往 '搜索'
2. 点击 '搜索'
4. 出现问题

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

3.2.44

### 下载模式是？

Browser

**Comment by TPAXcc** [comment]
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/91980905/5a11be85-fe94-4879-aeea-13b412ac5012)

**Comment by dawn-lc** [comment]
@TPAXcc 安装最新开发版看看有没有修复
