### ISSUE TITLE
[Suggest]: 建议添加侧边栏固定展开的功能

### ISSUE THREAD

**Issue by WallBreakerNO4** [dawn-lc/IwaraDownloadTool#200]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

其他（例如：XXX极速、XXX安全等）

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

3.2.52

### 描述你的建议

本人经常使用移动设备浏览I站（kiwibrowser），本脚本的侧边栏在移动设备上的互交非常不方便，经常误触。希望可以添加将侧边栏固定展开的选项，非常感谢

### 建议的具体描述

希望可以添加将侧边栏固定展开的选项

**Comment by dawn-lc** [comment]
@WallBreakerNO4 开发版中关闭了侧边栏动画效果，试试效果如何
