### ISSUE TITLE
[Bug]: 内容服务器转移后，解析失败

### ISSUE THREAD

**Issue by mole828** [dawn-lc/IwaraDownloadTool#202]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

在 2024-05-26 完成对旧服务器内容的迁移后，旧视频的解析出现问题

### 如何复现

找一个旧一些，进行转移的视频。（大致24年之前的）
进行下载会提示 “没有可供下载的视频”

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.58

### 下载模式是？

Aria2

**Comment by dawn-lc** [comment]
请检查下载画质检查功能配置

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/30336566/c81e5945-5432-434c-aeff-c0352708d0bf)
