### ISSUE TITLE
[Suggest]: Decrease show up time of pop-up notification

### ISSUE THREAD

**Issue by MizukiSorata** [dawn-lc/IwaraDownloadTool#203]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.58

### 描述你的建议

The pop-up notification show up time is too long. It makes user hard to operate setting interface.

**Comment by dawn-lc** [comment]
Please provide a screenshot of the page when the pop-up notification is displayed for too long

**Comment by MizukiSorata** [comment]
![GIF 2024-6-2 13-06-17](https://github.com/dawn-lc/IwaraDownloadTool/assets/171428395/b8826e74-5590-4026-94c9-6c1bd909af43)
如果增加一个关闭弹出通知的按钮会更好
It will be better if there is a button to close pop-up notification

**Comment by dawn-lc** [comment]
请参考 https://sleazyfork.org/zh-CN/scripts/422239-iwara-download-tool/discussions/243952
