### ISSUE TITLE
[Bug]: 当不存在`Source`画质时自动回退

### ISSUE THREAD

**Issue by WallBreakerNO4** [dawn-lc/IwaraDownloadTool#206]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

有些视频（[例子](https://www.iwara.tv/video/UFEbxetZk5n0Ed/2311)）没有`Source`画质，但有`540p`或者`360p`画质，这种情况下会解析不到下载链接而直接失败。希望能添加一个选项，让解析较高画质失败时可以回退到较低画质。

### 如何复现

1. 前往 https://www.iwara.tv/video/UFEbxetZk5n0Ed/2311 
2. 点击 `下载当前`
3. 出现问题

---

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

3.2.64

### 下载模式是？

Aria2

### 截图

![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/34301560/a8adf12b-92db-4dcb-a699-0e9421ec259d)

**Comment by dawn-lc** [comment]
#202
