### ISSUE TITLE
[Suggest]: 无法唤醒下载器接管下载

### ISSUE THREAD

**Issue by fool-kid** [dawn-lc/IwaraDownloadTool#208]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

最新

### 描述你的建议

我不是程序员、不能给出确切的问题、抱歉
我在使用过程中
点击下载后，浏览器弹出了一个网页
但是过了一会就消失了
不过，网页网址是能作为下载的url的
用的下载器是fdm
谢谢

**Comment by dawn-lc** [comment]
如果你的下载器没有捕获到下载，我建议你咨询你的下载开发者，但是FDM我了解过，如果需要使用FDM接管Edge浏览器的自带下载功能，请在Edge浏览器中安装由FDM提供的浏览器扩展。
