### ISSUE TITLE
[Bug]: 路径分割符问题

### ISSUE THREAD

**Issue by Lordcell** [dawn-lc/IwaraDownloadTool#214]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

当下载视频标题中出现“/”时，符号左边的所有标题内容均无法注入。

### 如何复现

选中带有“/”的视频，
选择下载所选，
下载标题自动注入选择框

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

V5.1.1

### 下载模式是？

Others

### 截图

![QQ图片20240704055537](https://github.com/dawn-lc/IwaraDownloadTool/assets/103607549/f4308e81-ac43-46bd-acf7-a568c0aa2944)
![QQ图片20240704055545](https://github.com/dawn-lc/IwaraDownloadTool/assets/103607549/18735bf6-a2f8-4210-88d7-c4202f77908f)

**Comment by dawn-lc** [comment]
麻烦确认脚本版本

**Comment by dawn-lc** [comment]
请更新至最新开发板检查问题是否修复。

**Comment by Lordcell** [comment]
目前版本3.2.70，问题已修复。
