### ISSUE TITLE
能否添加mmdfans批量下载支持？

### ISSUE THREAD

**Issue by nd002723** [dawn-lc/IwaraDownloadTool#217]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.70

### 描述你的建议

有些作者已经删号i站变成404了但是mmdfans上面有缓存依然能搜索作者名搜到对应的视频

**Comment by dawn-lc** [comment]
我已经尝试过接入该网站作为下载源，很遗憾mmdfans不支持使用id搜索视频，目前在mmdfans上只能使用视频标题或作者昵称来搜索，所以你需要指导作者昵称（不是账户名）或视频标题才能找到视频源。

**Comment by nd002723** [comment]
> 我已经尝试过接入该网站作为下载源，很遗憾mmdfans不支持使用id搜索视频，目前在mmdfans上只能使用视频标题或作者昵称来搜索，所以你需要指导作者昵称（不是账户名）或视频标题才能找到视频源。

我的意思不是以接入这里作为下载源的意思，而是支持直接在mmdfans批量勾选视频进行下载。
比如以已经删除的作者dlaldn为例，他本人已经在iwara上面删号了但是[mmdfans](https://mmdfans.net/?query=author:dlaldn)依然有他的视频我想去这里面勾选批量下载

**Comment by dawn-lc** [comment]
本项目为Iwara下载工具，增加对mmdfans的支持暂不在当前开发计划中，如有需要您可以fork本项目加以修改实现您所需的功能。
