### ISSUE TITLE
关于选中下载的问题

### ISSUE THREAD

**Issue by fskdj114514** [dawn-lc/IwaraDownloadTool#218]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.70

### 描述你的建议

点取消全部选中，只能取消当前浏览器页面的选中，如果在其他页面选中了，就算关闭了浏览器，脚本依然会记录选中，会导致可能在自己不知道的情况下，解析了大量的视频，

### 建议的具体描述

有什么方法可以清除脚本的缓存或所有选中吗

**Comment by dawn-lc** [comment]
功能已添加，请更新至最新开发版体验。
