### ISSUE TITLE
[Bug]: 为什么下载路径里的设置是无效的？

### ISSUE THREAD

**Issue by fanglangxinghai** [dawn-lc/IwaraDownloadTool#227]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

使用的默认下载路径是这个“/Iwara/%#AUTHOR#%/%#TITLE#%[%#ID#%].mp4”，但实际下载时，其实只有后面的“/%#TITLE#%[%#ID#%].mp4”这一段是有效的。比如，我chrome的下载位置是“F:\downloads”，那么下载视频就下载到“F:\downloads”下，并不会建立““/Iwara/%#AUTHOR#%/”的文件夹。

我是win10，chrome（最新版本）

### 如何复现

1. 前往 'iwara'
2. 点击 '下载所选'
3. 出现问题

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

5.1.1

### 下载模式是？

Others

### 截图

![2024-09-18 02_08_18-Window](https://github.com/user-attachments/assets/07763d6f-83a2-4095-bae6-f14233787efe)

**Comment by dawn-lc** [comment]
https://github.com/dawn-lc/IwaraDownloadTool/wiki/%E5%AE%89%E8%A3%85%E4%B8%8E%E5%88%9D%E5%A7%8B%E5%8C%96%E8%84%9A%E6%9C%AC#:~:text=%E8%AF%B7%E5%9C%A8%E2%80%9C%E4%B8%8B%E8%BD%BD%E5%88%B0%3A%20%E2%80%9D%E6%96%87%E6%9C%AC%E6%A1%86%E4%B8%AD%E8%BE%93%E5%85%A5%E6%82%A8%E5%B8%8C%E6%9C%9B%E4%B8%8B%E8%BD%BD%E7%9A%84%E8%A7%86%E9%A2%91%E4%BF%9D%E5%AD%98%E7%9A%84%E8%B7%AF%E5%BE%84%EF%BC%88Aria2%E3%80%81IwaraDownloader%E6%94%AF%E6%8C%81%E8%87%AA%E5%8A%A8%E5%88%9B%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E5%85%B6%E4%BB%96%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%BC%8F%E4%BB%85%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E4%BB%B6%E5%90%8D%EF%BC%89

**Comment by dawn-lc** [comment]
使用脚本原生支持的下载器（如Aria2或其他使用Aria2内核的下载器）下载到其他文件夹功能才能生效，因为Aria2有完善的API接口可供脚本调用。
使用其他下载器或浏览器原生下载功能皆不生效，因为浏览器并没有提供下载到指定位置的API给脚本。
