### ISSUE TITLE
[Suggest]: 

### ISSUE THREAD

**Issue by minecraftyusei** [dawn-lc/IwaraDownloadTool#228]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.95

### 描述你的建议

希望增加对下载文件自定义文件名时可供参考的命名规则表。想法来源是下面这张图：
![屏幕截图 2024-09-20 210416](https://github.com/user-attachments/assets/1c08a686-2626-4921-bf5d-99686f343505)

**Comment by dawn-lc** [comment]
![image](https://github.com/user-attachments/assets/b88673fd-bfd6-450e-887c-2ba8dc890680)

**Comment by dawn-lc** [comment]
%#NowTime:YYYY-MM-DD#%_%#AUTHOR#%_%#UploadTime:YYYY-MM-DD#%_%#TITLE#%_%#QUALITY#%[%#ID#%].MP4

在替换变量后结果是：

2024-02-19_ExampleAuthorID_2024-02-18_ExampleTitle_Source[ExampleID].MP4

**Comment by dawn-lc** [comment]
规则很简单
使用“%#”和“#%”包裹的是变量名称
在包裹内的":"是对时间变量的格式化字符串，例如： %#NowTime:YYYY-MM-DD#% --> 2024-09-20
其他文字随你咋改。

**Comment by dawn-lc** [comment]
#### 路径可用变量

* 下载时间 %#NowTime#%
* 发布时间 %#UploadTime#%
* 视频标题 %#TITLE#%
* 视频ID %#ID#%
* 视频作者 %#AUTHOR#%
* 视频作者(昵称) %#ALIAS#%
* 画质 %#QUALITY#%

  %\#NowTime:YYYY\-MM\-DD\#%\_%\#AUTHOR\#%\_%\#UploadTime:YYYY\-MM\-DD\#%\_%\#TITLE\#%\_%\#QUALITY\#%\[%\#ID\#%\]\.MP4

  输出：

  2024\-02\-19\_ExampleAuthorID\_2024\-02\-18\_ExampleTitle\_Source\[ExampleID\]\.MP4

**Comment by minecraftyusei** [comment]
> #### 路径可用变量
> * 下载时间 %#NowTime#%
> * 发布时间 %#UploadTime#%
> * 视频标题 %#TITLE#%
> * 视频ID %#ID#%
> * 视频作者 %#AUTHOR#%
> * 视频作者(昵称) %#ALIAS#%
> * 画质 %#QUALITY#%
>   %#NowTime:YYYY-MM-DD#%_%#AUTHOR#%_%#UploadTime:YYYY-MM-DD#%_%#TITLE#%_%#QUALITY#%[%#ID#%].MP4
>   输出：
>   2024-02-19_ExampleAuthorID_2024-02-18_ExampleTitle_Source[ExampleID].MP4

感谢作者回复
最后请教一下，我把规则修改为图一中的这个表达，它并没有在我下载的文件名里添加上“Iwara”。
![屏幕截图 2024-09-21 091741](https://github.com/user-attachments/assets/f3a8f3ee-00b5-4f6d-a2ff-748043d95d07)
要想实现图二中下面那个视频的命名规则（那个是直接用浏览器下载，它的文件名前面就会有一个Iwara的前缀）我应该怎么写呢？
![屏幕截图 2024-09-21 091838](https://github.com/user-attachments/assets/1e5860f6-4d35-49d8-951e-d2232969a186)

**Comment by dawn-lc** [comment]
> > #### 路径可用变量
> > * 下载时间 %#NowTime#%
> > * 发布时间 %#UploadTime#%
> > * 视频标题 %#TITLE#%
> > * 视频ID %#ID#%
> > * 视频作者 %#AUTHOR#%
> > * 视频作者(昵称) %#ALIAS#%
> > * 画质 %#QUALITY#%
> >   %#NowTime:YYYY-MM-DD#%_%#AUTHOR#%_%#UploadTime:YYYY-MM-DD#%_%#TITLE#%_%#QUALITY#%[%#ID#%].MP4
> >   输出：
> >   2024-02-19_ExampleAuthorID_2024-02-18_ExampleTitle_Source[ExampleID].MP4
> 
> 感谢作者回复
> 最后请教一下，我把规则修改为图一中的这个表达，它并没有在我下载的文件名里添加上“Iwara”。
> ![屏幕截图 2024-09-21 091741](https://github.com/user-attachments/assets/f3a8f3ee-00b5-4f6d-a2ff-748043d95d07)
> 要想实现图二中下面那个视频的命名规则（那个是直接用浏览器下载，它的文件名前面就会有一个Iwara的前缀）我应该怎么写呢？
> ![屏幕截图 2024-09-21 091838](https://github.com/user-attachments/assets/1e5860f6-4d35-49d8-951e-d2232969a186)
> 

请搜索什么是路径分割符，这是一个路径

**Comment by minecraftyusei** [comment]
> > > #### 路径可用变量
> > > 
> > > * 下载时间 %#NowTime#%
> > > * 发布时间 %#UploadTime#%
> > > * 视频标题 %#TITLE#%
> > > * 视频ID %#ID#%
> > > * 视频作者 %#AUTHOR#%
> > > * 视频作者(昵称) %#ALIAS#%
> > > * 画质 %#QUALITY#%
> > >   %#NowTime:YYYY-MM-DD#%_%#AUTHOR#%_%#UploadTime:YYYY-MM-DD#%_%#TITLE#%_%#QUALITY#%[%#ID#%].MP4
> > >   输出：
> > >   2024-02-19_ExampleAuthorID_2024-02-18_ExampleTitle_Source[ExampleID].MP4
> > 
> > 
> > 感谢作者回复
> > 最后请教一下，我把规则修改为图一中的这个表达，它并没有在我下载的文件名里添加上“Iwara”。
> > ![屏幕截图 2024-09-21 091741](https://private-user-images.githubusercontent.com/39985294/369586796-f3a8f3ee-00b5-4f6d-a2ff-748043d95d07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODI1NTEsIm5iZiI6MTcyNjg4MjI1MSwicGF0aCI6Ii8zOTk4NTI5NC8zNjk1ODY3OTYtZjNhOGYzZWUtMDBiNS00ZjZkLWEyZmYtNzQ4MDQzZDk1ZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAxMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTM4YTU2NDNhMGJkZGQ1MmJhZDkxYjI3ZTMwYzhhNjAyYmUxMTU1OTBiMGZiZTY2ZmQyOTUyZjEwNDdjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U6uGn1UbMpsntiCPGjV36rIizYxALoDDkqN6_djitFQ)
> > 要想实现图二中下面那个视频的命名规则（那个是直接用浏览器下载，它的文件名前面就会有一个Iwara的前缀）我应该怎么写呢？
> > ![屏幕截图 2024-09-21 091838](https://private-user-images.githubusercontent.com/39985294/369586833-1e5860f6-4d35-49d8-951e-d2232969a186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODI1NTEsIm5iZiI6MTcyNjg4MjI1MSwicGF0aCI6Ii8zOTk4NTI5NC8zNjk1ODY4MzMtMWU1ODYwZjYtNGQzNS00OWQ4LTk1MWUtZDIyMzI5NjlhMTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAxMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MjJkN2Y3YjZmYjU3ZDQxNDBhOGNlMzJhN2EwZDI2ZjU0NDhmZGViMGFjNTQ1Nzc1MTcwMTQ3NTgxM2YwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zw1WCNx4hB-UQ7aeb3tLHqzJVBSdwJoHaVK-JwL7Cjw)
> 
> 请搜索什么是路径分割符，这是一个路径

好的，小白感谢作者回复(´。＿。｀)

**Comment by dawn-lc** [comment]
> > > > #### 路径可用变量
> > > > 
> > > > * 下载时间 %#NowTime#%
> > > > * 发布时间 %#UploadTime#%
> > > > * 视频标题 %#TITLE#%
> > > > * 视频ID %#ID#%
> > > > * 视频作者 %#AUTHOR#%
> > > > * 视频作者(昵称) %#ALIAS#%
> > > > * 画质 %#QUALITY#%
> > > >   %#NowTime:YYYY-MM-DD#%_%#AUTHOR#%_%#UploadTime:YYYY-MM-DD#%_%#TITLE#%_%#QUALITY#%[%#ID#%].MP4
> > > >   输出：
> > > >   2024-02-19_ExampleAuthorID_2024-02-18_ExampleTitle_Source[ExampleID].MP4
> > > 
> > > 
> > > 感谢作者回复
> > > 最后请教一下，我把规则修改为图一中的这个表达，它并没有在我下载的文件名里添加上“Iwara”。
> > > ![屏幕截图 2024-09-21 091741](https://private-user-images.githubusercontent.com/39985294/369586796-f3a8f3ee-00b5-4f6d-a2ff-748043d95d07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODI1NTEsIm5iZiI6MTcyNjg4MjI1MSwicGF0aCI6Ii8zOTk4NTI5NC8zNjk1ODY3OTYtZjNhOGYzZWUtMDBiNS00ZjZkLWEyZmYtNzQ4MDQzZDk1ZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAxMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YTM4YTU2NDNhMGJkZGQ1MmJhZDkxYjI3ZTMwYzhhNjAyYmUxMTU1OTBiMGZiZTY2ZmQyOTUyZjEwNDdjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U6uGn1UbMpsntiCPGjV36rIizYxALoDDkqN6_djitFQ)
> > > 要想实现图二中下面那个视频的命名规则（那个是直接用浏览器下载，它的文件名前面就会有一个Iwara的前缀）我应该怎么写呢？
> > > ![屏幕截图 2024-09-21 091838](https://private-user-images.githubusercontent.com/39985294/369586833-1e5860f6-4d35-49d8-951e-d2232969a186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODI1NTEsIm5iZiI6MTcyNjg4MjI1MSwicGF0aCI6Ii8zOTk4NTI5NC8zNjk1ODY4MzMtMWU1ODYwZjYtNGQzNS00OWQ4LTk1MWUtZDIyMzI5NjlhMTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAxMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MjJkN2Y3YjZmYjU3ZDQxNDBhOGNlMzJhN2EwZDI2ZjU0NDhmZGViMGFjNTQ1Nzc1MTcwMTQ3NTgxM2YwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zw1WCNx4hB-UQ7aeb3tLHqzJVBSdwJoHaVK-JwL7Cjw)
> > 
> > 请搜索什么是路径分割符，这是一个路径
> 
> 好的，小白感谢作者回复(´。＿。｀)

您需要自定义您的下载位置与文件重命名

请在“下载到: ”文本框中输入您希望下载的视频保存的路径（Aria2、IwaraDownloader支持自动创建文件夹，其他下载模式仅支持自定义文件名）


默认的路径含义是：另存为 根目录 中的 Iwara 文件夹 中的 %#AUTHOR#% 文件夹 下的 %#TITLE#%[%#ID#%].mp4

如果是windows用户，含义就是：另存为 C盘 中的 Iwara 文件夹 中的 %#AUTHOR#% 文件夹 下的 %#TITLE#%[%#ID#%].mp4
