### ISSUE TITLE
[Bug]: 开启插件后页面崩溃

### ISSUE THREAD

**Issue by ZFEVVV** [dawn-lc/IwaraDownloadTool#240]
### 在反馈之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本
- [ ] 我没有完成以上步骤，只是闭眼选中了所有的复选框

### 描述你的问题

前几日使用无问题 今天打开主页就显示页面崩溃 关闭插件后页面正常 插件版本为最新

### 如何复现

1. 前往 '...'
2. 点击 '....'
4. 出现问题

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.105

### 下载模式是？

Others

### 截图

![222444](https://github.com/user-attachments/assets/80768529-2a45-41d3-a0d6-dba98c198e79)

**Comment by dawn-lc** [comment]
请更新至最新预览版

**Comment by Voidnickyname** [comment]
问题照旧

chrome版本
![image](https://github.com/user-attachments/assets/7de577a8-b57c-4f03-8958-fb8df2b4c92d)
油猴版本和插件版本
![image](https://github.com/user-attachments/assets/e518c4c1-95b6-4e68-8940-2de5917f16b8)
预览版安装方式
![image](https://github.com/user-attachments/assets/d9915bab-04e7-4ad6-868a-1a916e7f0dd0)
启用结果（暂停所有chrome插件除油后+暂停所有其他油猴插件）
![image](https://github.com/user-attachments/assets/e7c0bfea-7b4d-48d0-9742-a8262484066f)
关闭本插件
![image](https://github.com/user-attachments/assets/8007d026-df3d-4601-922d-f67023d315e4)

**Comment by Voidnickyname** [comment]
测试了用脚本猫代替油猴，关闭油猴的情况下，访问出现同样情况，
启用脚本猫但关闭本脚本，访问正常

**Comment by dawn-lc** [comment]
控制台输出发一下

**Comment by dawn-lc** [comment]
我本地复现不了

**Comment by Voidnickyname** [comment]
需要的是这个吗？
![image](https://github.com/user-attachments/assets/c9196cab-f030-4a28-9112-63aaffa35c46)

搜了下debugger的方式，不确定弄得对不对
![image](https://github.com/user-attachments/assets/9fb58f0a-7ae0-4896-984a-01a6fe298e7a)

**Comment by Voidnickyname** [comment]
Sentry disabled.
main.48e22ea8acfc887ca2d1.js:2 Build 3.2.4 at Sun, 10 Nov 2024 13:35:52 GMT
userscript.html?name=Iwara-Download-Tool.user.js&id=ab289ad4-9399-43f8-964a-4fda6fc5c79d:1727 Iwara 批量下载工具加载完成公告: 添加取消所有选中按钮，点击该按钮将会清空所有选中，请谨慎操作！调整下载当前视频功能，默认不再检查第三方下载链接以及是否关注作者和喜欢该视频。
main.48e22ea8acfc887ca2d1.js:2 Service worker registered.
main.48e22ea8acfc887ca2d1.js:2 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at main.48e22ea8acfc887ca2d1.js:2:1016710
    at o (main.48e22ea8acfc887ca2d1.js:2:1016772)
    at chunk-5262.9beef65a083691402fd9.js:1:1424
    at Array.reduce (<anonymous>)
    at k (chunk-5262.9beef65a083691402fd9.js:1:1368)
    at Yo (main.48e22ea8acfc887ca2d1.js:2:896567)
    at Ri (main.48e22ea8acfc887ca2d1.js:2:905416)
    at Cs (main.48e22ea8acfc887ca2d1.js:2:943691)
    at dl (main.48e22ea8acfc887ca2d1.js:2:935248)
    at fl (main.48e22ea8acfc887ca2d1.js:2:935173)
ns @ main.48e22ea8acfc887ca2d1.js:2Understand this errorAI
main.48e22ea8acfc887ca2d1.js:2 Caught error TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at main.48e22ea8acfc887ca2d1.js:2:1016710
    at o (main.48e22ea8acfc887ca2d1.js:2:1016772)
    at chunk-5262.9beef65a083691402fd9.js:1:1424
    at Array.reduce (<anonymous>)
    at k (chunk-5262.9beef65a083691402fd9.js:1:1368)
    at Yo (main.48e22ea8acfc887ca2d1.js:2:896567)
    at Ri (main.48e22ea8acfc887ca2d1.js:2:905416)
    at Cs (main.48e22ea8acfc887ca2d1.js:2:943691)
    at dl (main.48e22ea8acfc887ca2d1.js:2:935248)
    at fl (main.48e22ea8acfc887ca2d1.js:2:935173) Object

**Comment by dawn-lc** [comment]
知道问题了，尝试清空IndexedDB

**Comment by Rimliya** [comment]
清除indexed DB后可以使用了

**Comment by Voidnickyname** [comment]
清除indexed DB后确认恢复

**Comment by AKIRAasf** [comment]
啊这 咋清啊 大佬们 有没有链接或者关键词啊
