### ISSUE TITLE
[Bug]: 用户页面未正常注入选择框

### ISSUE THREAD

**Issue by 114514-end** [dawn-lc/IwaraDownloadTool#255]
### 在反馈之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

更新后无法使用，有尝试安装旧版本但还是无法使用

### 如何复现

1. 前往 iwara
2. 没有显示UI

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.134

### 下载模式是？

Others

### 截图

![屏幕截图 2024-11-22 055925](https://github.com/user-attachments/assets/7a925faa-0768-4dd0-a62d-d47c4ef772fe)
![屏幕截图 2024-11-22 060004](https://github.com/user-attachments/assets/57110c7c-6b5e-4d2a-a886-dd824160e4bd)
已经尝试重新安装油猴和脚本，均无效

**Comment by dawn-lc** [comment]
![图片](https://github.com/user-attachments/assets/ad06fffd-9e4b-4d53-bf8f-87ab4a3342cd)
请提供正确的信息以便排查问题原因

**Comment by Rimliya** [comment]
![image](https://github.com/user-attachments/assets/a03d4e82-3688-408b-a2a7-c30a9e9e2c73)
![image](https://github.com/user-attachments/assets/a6cce36c-7347-4912-a4ee-5441adf695d8)
注入框确实没有了

**Comment by ZFEVVV** [comment]
用户页面页面下注入框消失，其他页面正常
![image](https://github.com/user-attachments/assets/d37ca0b8-65f0-4cc3-ae78-d4dd9e58f819)
![image](https://github.com/user-attachments/assets/22b0cab8-9b0e-4972-b8ec-acab95f4548a)
![image](https://github.com/user-attachments/assets/d1dfca67-3568-45ea-b7e9-260a69d5f1c4)

**Comment by dawn-lc** [comment]
正在排查

**Comment by dawn-lc** [comment]
@ZFEVVV

**Comment by ZFEVVV** [comment]
> @ZFEVVV

已解决

**Comment by Aixve** [comment]
![{EAACF312-6BE3-485c-80FB-7A0CA3DFF993}](https://github.com/user-attachments/assets/91f042ea-2c21-4a04-8149-184142913580)
在当前用户界面或作品界面时该用户的作品没有选择框，但推荐的其他用户的视频就有选择框

**Comment by dawn-lc** [comment]
> ![{EAACF312-6BE3-485c-80FB-7A0CA3DFF993}](https://private-user-images.githubusercontent.com/46237951/389178282-91f042ea-2c21-4a04-8149-184142913580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDUzMDUsIm5iZiI6MTczMjM0NTAwNSwicGF0aCI6Ii80NjIzNzk1MS8zODkxNzgyODItOTFmMDQyZWEtMmMyMS00YTA0LTgxNDktMTg0MTQyOTEzNTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA2NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNGYxYjMxMDdkNDBhOWEyNTZlYmY0ZjQwNDhhZDAwYjMyNmQyMjc3ODE0N2RlMmM1YjRhZjY4ZWI2MDA0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X8NFrSoqgF2IHjbf5AuW4GCUet14B9Vo2Kc_ZFhZolg) 在当前用户界面或作品界面时该用户的作品没有选择框，但推荐的其他用户的视频就有选择框

更新至最新预览版看看有没有问题

**Comment by Aixve** [comment]
> > ![{EAACF312-6BE3-485c-80FB-7A0CA3DFF993}](https://private-user-images.githubusercontent.com/46237951/389178282-91f042ea-2c21-4a04-8149-184142913580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDUzMDUsIm5iZiI6MTczMjM0NTAwNSwicGF0aCI6Ii80NjIzNzk1MS8zODkxNzgyODItOTFmMDQyZWEtMmMyMS00YTA0LTgxNDktMTg0MTQyOTEzNTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA2NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNGYxYjMxMDdkNDBhOWEyNTZlYmY0ZjQwNDhhZDAwYjMyNmQyMjc3ODE0N2RlMmM1YjRhZjY4ZWI2MDA0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X8NFrSoqgF2IHjbf5AuW4GCUet14B9Vo2Kc_ZFhZolg) 在当前用户界面或作品界面时该用户的作品没有选择框，但推荐的其他用户的视频就有选择框
> 
> 更新至最新预览版看看有没有问题

更新至预览版以后选择框恢复，谢谢。
