### ISSUE TITLE
[Bug]: 找不到配置中对应的语言导致UI无法显示

### ISSUE THREAD

**Issue by a1348196037** [dawn-lc/IwaraDownloadTool#257]
### 在反馈之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

在语言中维护错误的语言导致按钮不会显示，无法修改只能重新安装猴油再重新安装插件

### 如何复现

![image](https://github.com/user-attachments/assets/5bad8a23-8301-4535-b316-f63ef1dd0016)

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.137

### 下载模式是？

Others

### 截图

![image](https://github.com/user-attachments/assets/61e1690e-e5b8-4fb8-822d-b082d28394ee)
修改后：
return isNullOrUndefined(i18n[config2.language]) ? !isNullOrUndefined(i18n[env]) ? env : !isNullOrUndefined(i18n[main]) ? main : "en" : config2.language;

**Comment by dawn-lc** [comment]
无需重装，在篡改猴的脚本设置页面中有一个存储选项卡，里面是脚本配置

**Comment by dawn-lc** [comment]
另外直接修改打包后的user.js是不推荐的，如需提供修改可以在dev分支提交pr，提交合并后会自动打包并发布预览版。
