### ISSUE TITLE
[Bug]: 用户视频页没有选择框

### ISSUE THREAD

**Issue by WallBreakerNO4** [dawn-lc/IwaraDownloadTool#261]
### 在反馈之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

如题，再用户界面没有选择框
![image](https://github.com/user-attachments/assets/c7114d81-79af-4884-b55b-e7ad9d7c8f99)
点击 `开关选择框` 也没用

### 如何复现

1. 进入任意用户界面
2. 选择框消失不见
3. `开关选择框` 按钮没用

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey Beta

### 脚本的版本是？

3.2.134

### 下载模式是？

Aria2

### 截图

![image](https://github.com/user-attachments/assets/61a4503d-73af-4e9a-9179-1106f34b9c3c)
![image](https://github.com/user-attachments/assets/e53ab4e2-91bd-4499-a250-9ff2c53cc1dd)

**Comment by dawn-lc** [comment]
https://github.com/dawn-lc/IwaraDownloadTool/issues/255
