### ISSUE TITLE
[Suggest]: 添加新功能

### ISSUE THREAD

**Issue by kkmnsk** [dawn-lc/IwaraDownloadTool#262]
### 在提出建议之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提出建议之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 使用的浏览器是？

Microsoft Edge

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.143

### 描述你的建议

可以添加一个下载时自动收藏的功能吗

**Comment by dawn-lc** [comment]
打开设置中的“自动点赞选中的视频”
