### ISSUE TITLE
[Bug]: %#UploadTime#%参数导致推送aria2报错误16

### ISSUE THREAD

**Issue by Voidnickyname** [dawn-lc/IwaraDownloadTool#272]
### 在反馈之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版的脚本

### 描述你的问题

今早下载视频时，遇到推送aria2报 发生错误16 
检查发现生成文件名的 [%#UploadTime%] 参数变为了 2024-12-18T21:33:58.000Z 样式，前天及之前一直是 2024-12-18 样式

按 https://github.com/dawn-lc/IwaraDownloadTool 说明，
调整为 %#UploadTime:YYYY-MM-DD#% 后，依然无效，依然是按 2024-12-18T21:33:58.000Z 传递
见截图aria2的失败任务文件名

脚本版本从153更新到155，问题照旧

### 如何复现

1、点击设置
2、下载到配置改为
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime%][%#ID#%] %#TITLE#% [%#QUALITY#%].mp4
或
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime:YYYY-MM-DD#%][%#ID#%] %#TITLE#% [%#QUALITY#%].mp4
3、随意下载一个视频

### 使用的浏览器是？

Chrome

### 使用的脚本管理器是？

Tampermonkey

### 脚本的版本是？

3.2.155

### 下载模式是？

Aria2

### 截图

截图
自下而上的3次尝试，分别对应：

Sucess
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#ID#%] %#TITLE#% [%#QUALITY#%].mp4

Failure
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime%][%#ID#%] %#TITLE#% [%#QUALITY#%].mp4
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime:YYYY-MM-DD#%][%#ID#%] %#TITLE#% [%#QUALITY#%].mp4

![image](https://github.com/user-attachments/assets/9b030344-27b6-47c9-81d3-fc49a15bbd3b)
![image](https://github.com/user-attachments/assets/ca841452-93e9-41c0-9a28-fa74f7241857)
![image](https://github.com/user-attachments/assets/1c1f3588-898f-4563-bf82-e7eb32d85336)

**Comment by Voidnickyname** [comment]
![image](https://github.com/user-attachments/assets/bc8bcb15-03f6-4e59-b5ad-974d481d1fd2)
![image](https://github.com/user-attachments/assets/a5e21af2-7bae-432a-a3ff-b56e565a0e51)

aria2的截图补充状态信息

**Comment by dawn-lc** [comment]
请更新至最新预览版检查问题是否解决。

**Comment by Voidnickyname** [comment]
怎么更新预览版有guidance吗？

**Comment by Voidnickyname** [comment]
找到更新方法了。
测试结果
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime:YYYY-MM-DD#%][%#ID#%] %#TITLE#% 
ok
/%#AUTHOR#%/[MMD][%#AUTHOR#%][%#ALIAS#%][%#UploadTime#%][%#ID#%] %#TITLE#% 
跟之前的情况一样

和主页说明文档保持一直，应该是通过了
