### ISSUE TITLE
IwaraDownloader 测试

### ISSUE THREAD

**Issue by dawn-lc** [dawn-lc/IwaraDownloadTool#72]
欢迎尝试 https://github.com/dawn-lc/IwaraDownloader
2023/5/19 更新
[IwaraDownloader_win-x64.zip](https://github.com/dawn-lc/IwaraDownloadTool/files/11509583/IwaraDownloader_win-x64.zip)
[IwaraDownloader_linux-x64.tar.gz](https://github.com/dawn-lc/IwaraDownloadTool/files/11509618/IwaraDownloader_linux-x64.tar.gz)

**Comment by dotaraku** [comment]
试了下，推送下载是没有什么问题，但是相比aria少点人性化功能
1.下载无法了解下载进度，是否无网速卡住下载也不太清除
2.下载完如果也能新建作者文件夹分类进去就好了（aria的通道默认是这样子的，批量扒好几个作者不用再去复制黏贴）

**Comment by dawn-lc** [comment]
> 下载完如果也能新建作者文件夹分类进去就好了（aria的通道默认是这样子的，批量扒好几个作者不用再去复制黏贴）

只要你路径写对了会自动创建的例如"Z:\iwara\%#AUTHOR#%\%#TITLE#%[%#ID#%].MP4"就会创建"Z:\iwara\XXXX\NNNNN[sssssssss].MP4"

**Comment by dawn-lc** [comment]
你可以试试 用播放器打开 http://127.0.0.1:6800/playlist.xspf

**Comment by dawn-lc** [comment]
理论上来说vlc 和 Potplayer都可以直接获取到播放列表,默认是按照视频上传时间排序的
http://127.0.0.1:6800/playlist.xspf?orderby=size 可以获取到按照文件大小排列的播放列表
http://127.0.0.1:6800/playlist.xspf?orderby=author&key=%#author#% 可以获取到作者用户名或昵称包含%#author#%的所有视频  例如: http://127.0.0.1:6800/playlist.xspf?orderby=author&key=三仁月饼 就可以 获取到作者用户名或昵称包含三仁月饼的所有视频
http://127.0.0.1:6800/playlist.xspf?orderby=name&key=%#name#% 可以获取到视频标题中包含%#name#%的所有视频  例如: http://127.0.0.1:6800/playlist.xspf?orderby=name&key=mmd 就可以 获取到视频标题中包含mmd 的所有视频

**Comment by HANA00** [comment]
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (merli.iwara.tv:443)。这是什么问题啊

**Comment by owowowol** [comment]
Failed to bind to address http://0.0.0.0:6800: address already in use.
這是啥阿

**Comment by dawn-lc** [comment]
> 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (merli.iwara.tv:443)。这是什么问题啊

下载器没法连接到i站，请确认你的网络情况

**Comment by shadow-soldier** [comment]
![image](https://user-images.githubusercontent.com/41889621/230086011-fa0702b9-629b-414a-9b3b-d10aeb4ff66e.png)
这个是哪里设置有问题吗

**Comment by shadow-soldier** [comment]
而且这个提示不会自己消失，我打开了一个视频之后还是一直在上方

**Comment by dawn-lc** [comment]
这是脚本在校验配置和下载器是否正常，你配置不对

**Comment by shadow-soldier** [comment]
是路径里面的斜杠错了，我改成正确的了，但是还是提示错误，其他配置我都没有改过
![image](https://user-images.githubusercontent.com/41889621/230091733-14e02c38-2263-4d22-809f-03f829a86bd4.png)
![image](https://user-images.githubusercontent.com/41889621/230091884-6ecff37f-883f-457c-bae8-788e390be7b4.png)
还有就是这个报错的提示不会自己消失，我保存几次就出现几个，一直停在上方

**Comment by dawn-lc** [comment]
@shadow-soldier 启动iwaradownloader后的命令行界面有截图吗？

**Comment by shadow-soldier** [comment]
![image](https://user-images.githubusercontent.com/41889621/230591655-07d99f9a-23fd-4529-ac54-a1bb17c8dbf1.png)
昨天i站崩了没法试，今天试了一下，如图所示

**Comment by HANA00** [comment]
@dawn-lc ，大佬，最新的3.0.380版本加载后会让页面全白不显示东西

**Comment by saufall** [comment]
> 是路径里面的斜杠错了，我改成正确的了，但是还是提示错误，其他配置我都没有改过 ![image](https://user-images.githubusercontent.com/41889621/230091733-14e02c38-2263-4d22-809f-03f829a86bd4.png) ![image](https://user-images.githubusercontent.com/41889621/230091884-6ecff37f-883f-457c-bae8-788e390be7b4.png) 还有就是这个报错的提示不会自己消失，我保存几次就出现几个，一直停在上方

我开启iwara downloader的时候也无法设置成功。但是点aria2的却成功了。没有安装aria2。尝试下载他说发送到aria2了但是没有下载的迹象。是不是两个下载器搞混了

**Comment by dawn-lc** [comment]
> > 是路径里面的斜杠错了，我改成正确的了，但是还是提示错误，其他配置我都没有改过 ![image](https://user-images.githubusercontent.com/41889621/230091733-14e02c38-2263-4d22-809f-03f829a86bd4.png) ![image](https://user-images.githubusercontent.com/41889621/230091884-6ecff37f-883f-457c-bae8-788e390be7b4.png) 还有就是这个报错的提示不会自己消失，我保存几次就出现几个，一直停在上方
> 
> 我开启iwara downloader的时候也无法设置成功。但是点aria2的却成功了。没有安装aria2。尝试下载他说发送到aria2了但是没有下载的迹象。是不是两个下载器搞混了

iwara downloader的命令行界面需要保持开启, 推送成功后会在命令行界面上显示开始下载

**Comment by dawn-lc** [comment]
> @dawn-lc ，大佬，最新的3.0.380版本加载后会让页面全白不显示东西

已在3.1.0以上版本修复, 请及时更新, ### **反馈bug请单独创建issue**

**Comment by z78966789** [comment]
![image](https://user-images.githubusercontent.com/111133655/234295857-26064261-c2f7-4bbf-b830-00707dd2aa77.png)
请问这个怎么办

**Comment by AKIRAasf** [comment]
> > ![image](https://user-images.githubusercontent.com/111133655/234295857-26064261-c2f7-4bbf-b830-00707dd2aa77.png)
> > 请问这个怎么办
> 
> 我检查一下是啥问题

请问我也遇到这个问题了    解决了么

**Comment by dawn-lc** [comment]
更新试试

**Comment by 2ciyv** [comment]
在推送 【R-18】鈴谷／ライアーダンス（紳士ハンド）　固定カメラver_[dnbz2tknefkmm0r1] 下载任务到IwaraDownloader过程中出现错误!
错误信息: Cannot add value because header 'Authorization' does not support multiple values.
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/50177664/24d7fcff-6cf8-47e8-953a-e6ce93489614)
![image](https://github.com/dawn-lc/IwaraDownloadTool/assets/50177664/1ce79045-0020-498b-b59d-c47c07cd7e0c)

**Comment by AKIRAasf** [comment]
> [2ciyv](/2ciyv)

同样也是这个问题

**Comment by dawn-lc** [comment]
> 在推送 【R-18】鈴谷／ライアーダンス（紳士ハンド）　固定カメラver_[dnbz2tknefkmm0r1] 下载任务到IwaraDownloader过程中出现错误! 错误信息: Cannot add value because header 'Authorization' does not support multiple values.
> 
> ![image](https://user-images.githubusercontent.com/50177664/240685273-24d7fcff-6cf8-47e8-953a-e6ce93489614.png) ![image](https://user-images.githubusercontent.com/50177664/240685309-1ce79045-0020-498b-b59d-c47c07cd7e0c.png) ![8K1$PCM4ZHI22~WVRP$FQ0M](https://user-images.githubusercontent.com/50177664/240687435-24372624-8e35-46cf-afce-b769ab900b76.png)

请升级至 Iwara Download Tool 以及 Iwara Downloader 至最新版开发版
Iwara Download Tool 开发板 => https://github.com/dawn-lc/IwaraDownloadTool/raw/dev/dist/IwaraDownloadTool.user.js
Iwara Downloader 源码 => https://github.com/dawn-lc/IwaraDownloader

**Comment by dawn-lc** [comment]
后续有关[IwaraDownloader](https://github.com/dawn-lc/IwaraDownloader)的反馈将会迁移到独立的项目中.
[bug提交请点击此处](https://github.com/dawn-lc/IwaraDownloader/issues/new?assignees=dawn-lc&labels=BUG&projects=&template=%E5%8F%8D%E9%A6%88bug.md&title=%5BBUG%5D)

**Comment by Barleytea2333** [comment]
大佬，这玩意用不明白啊，把脚本直接安装到Tampermonkey上，进入视频页面就这样，
保存了也使用不了啊，是我越少什么东西吗？
![111](https://github.com/dawn-lc/IwaraDownloadTool/assets/90115232/628c4588-4aa7-44f6-b870-35d8ad509a34)

**Comment by Barleytea2333** [comment]
大佬，怎么使用啊，把脚本安装到Tampermonkey上，用浏览器打开视频页面就出现这个，保存就开始报错，是我缺少了什么东西吗？
![111](https://github.com/dawn-lc/IwaraDownloadTool/assets/90115232/8393f87d-70c0-4cd1-b079-1a82b8a9869b)
